filter:
  excluded_paths:
    - tests/*
checks:
  php:
    code_rating: true
    duplication: true
build:
  tests:
    override:
      -
        command: 'phpunit --coverage-clover=tests/logs/clover.xml'
        coverage:
          file: 'tests/logs/clover.xml'
          format: 'php-clover'
