language: php
php:
  - 5.5
  - 5.6
  - 7
  - hhvm
before_script:
  - composer self-update
  - composer install
script:
  - mkdir -p tests/logs
  - chmod -R 777 tests/logs
  - phpunit
after_script:
  - php vendor/bin/coveralls -v
